using CairoMakie
using IsoconversionalAnalysis
using Printf
using Statistics

const PROJECT_ROOT = normpath(joinpath(@__DIR__, ".."))
const DEFAULT_REPORT = joinpath(PROJECT_ROOT, "docs", "deconvolution_audit.md")
const DEFAULT_MACHINE_REPORT = joinpath(
    PROJECT_ROOT, "docs", "audits", "m5_deconvolution_results.toml"
)
const DEFAULT_FIGURE_DIRECTORY = joinpath(PROJECT_ROOT, "docs", "figures", "m5")

function experiment_metadata(experiment::ProcessedExperiment)
    composition = round(Int, 100 * experiment.composition.waste_tire)
    rate = round(Int, experiment.diagnostics.measured_heating_rate_K_per_min)
    return (composition=composition, rate=rate)
end

function candidate_result(comparison::PeakCountComparison, peak_count::Int)
    return only(filter(result -> result.peak_count == peak_count, comparison.results))
end

function run_independent_audit(processed, config)
    return Dict(
        experiment.source_id => compare_peak_counts(experiment, config) for
        experiment in processed
    )
end

function run_joint_audit(processed, comparisons, config)
    results = Dict{Int,JointDeconvolutionResult}()
    for composition in (0, 25, 50, 75, 100)
        group = sort(
            filter(
                experiment ->
                    round(Int, 100 * experiment.composition.waste_tire) == composition,
                processed,
            );
            by=experiment -> experiment.source_id,
        )
        independent = [
            candidate_result(comparisons[experiment.source_id], 3) for experiment in group
        ]
        results[composition] = fit_joint_deconvolution(
            group, 3; configuration=config.deconvolution, independent_results=independent
        )
    end
    return results
end

function format_number(value; digits=3)
    return isfinite(value) ? @sprintf("%.*f", digits, value) : "not available"
end

function count_values(values)
    return join(
        ["$value × $(count(==(value), values))" for value in sort(unique(values))], ", "
    )
end

function write_markdown(path, processed, comparisons, joint_results, config)
    raw_counts = [
        comparison.criterion_minimum_peak_count for comparison in values(comparisons)
    ]
    selected_counts = [comparison.selected_peak_count for comparison in values(comparisons)]
    joint_supported = all(
        result ->
            result.diagnostics.converged &&
            result.diagnostics.relative_objective_increase <= 0.05,
        values(joint_results),
    )
    open(path, "w") do io
        println(io, "# M5 Fraser–Suzuki deconvolution audit")
        println(io)
        println(io, "Generated by `scripts/audit_deconvolution.jl` on 2026-08-17.")
        println(io)
        println(io, "## Scope and frozen contract")
        println(io)
        println(
            io,
            "The audit decomposes `dalpha/dT` for all 20 dynamic calibration experiments " *
            "over exact first-upward conversion crossings from " *
            "$(config.deconvolution.fit_conversion_range[1]) to " *
            "$(config.deconvolution.fit_conversion_range[2]). The 15 ramp-and-hold " *
            "experiments remain held out. No peak is assigned a chemical identity.",
        )
        println(io)
        println(
            io,
            "Each candidate uses ordered centers separated by at least " *
            "$(config.deconvolution.minimum_center_separation_K) K, nonnegative heights, " *
            "skew bounds $(config.deconvolution.skew_bounds), width bounds " *
            "$(config.deconvolution.width_bounds_K) K, and deterministic " *
            "$(config.deconvolution.multistart_count)-start L-BFGS optimization. " *
            "The fit never clips negative measured derivative values.",
        )
        println(io)
        println(
            io,
            "The predeclared synthetic gates require center recovery within 4 K, component " *
            "area-fraction recovery within 0.04, RMSE below `5e-5 K^-1`, correct BIC " *
            "selection under deterministic unstructured noise, and joint-fit order invariance.",
        )
        println(io)
        println(io, "## Peak-count comparison")
        println(io)
        println(io, "Raw BIC minima: $(count_values(raw_counts)).")
        println(io)
        println(
            io,
            "Final selections after structural filtering: $(count_values(selected_counts)).",
        )
        println(io)
        println(
            io,
            "A raw criterion minimum is not automatically accepted. Candidates are " *
            "excluded from selection when they do not converge, are locally rank/condition " *
            "deficient, activate a physical bound or minimum center separation, or assign " *
            "less than $(100 * config.deconvolution.minimum_component_area_fraction)% of " *
            "the reconstructed area to a component.",
        )
        println(io)
        println(
            io,
            "If no candidate passes every structural check, the raw criterion minimum is " *
            "retained with a `warning` status rather than silently dropping the experiment.",
        )
        println(io)
        println(
            io,
            "| Experiment | Tire dry mass | Rate (K/min) | Raw BIC minimum | Selected | Selection status | RMSE (K⁻¹) | R² | Area error | Max abs. correlation |",
        )
        println(io, "|---|---:|---:|---:|---:|---|---:|---:|---:|---:|")
        for experiment in sort(processed; by=value -> value.source_id)
            metadata = experiment_metadata(experiment)
            comparison = comparisons[experiment.source_id]
            selected = candidate_result(comparison, comparison.selected_peak_count)
            diagnostics = selected.diagnostics
            println(
                io,
                "| `$(experiment.source_id)` | $(metadata.composition)% | $(metadata.rate) | $(comparison.criterion_minimum_peak_count) | $(comparison.selected_peak_count) | `$(comparison.status)` | $(format_number(diagnostics.root_mean_square_error; digits=6)) | $(format_number(diagnostics.r_squared; digits=4)) | $(format_number(100 * diagnostics.relative_area_error; digits=2))% | $(format_number(diagnostics.maximum_absolute_parameter_correlation; digits=4)) |",
            )
        end
        println(io)
        println(
            io,
            "![Representative deconvolution](figures/m5/representative_deconvolution.svg)",
        )
        println(io)
        println(io, "![Peak-count selections](figures/m5/peak_count_selection.svg)")
        println(io)
        println(io, "## Joint multi-rate evaluation")
        println(io)
        println(
            io,
            "The joint experiment shares skew by ordered component while retaining " *
            "rate-specific heights, centers, and widths. Its objective is compared with " *
            "the corresponding independent three-peak fits on the same downsampled points.",
        )
        println(io)
        println(
            io, "| Tire dry mass | Shared skews | Relative objective increase | Status |"
        )
        println(io, "|---:|---|---:|---|")
        for composition in (0, 25, 50, 75, 100)
            result = joint_results[composition]
            skew_label = join(format_number.(result.shared_skews; digits=3), ", ")
            println(
                io,
                "| $composition% | $skew_label | $(format_number(100 * result.diagnostics.relative_objective_increase; digits=2))% | `$(result.diagnostics.status)` |",
            )
        end
        println(io)
        if joint_supported
            println(
                io,
                "Every shared-skew joint fit converged within a 5% objective increase. The " *
                "joint formulation is retained as a supported M5 analysis, while independent " *
                "fits remain necessary for peak-count comparison.",
            )
        else
            println(
                io,
                "At least one shared-skew joint fit fails the 5% objective-increase gate or " *
                "does not converge. Joint fitting remains an evaluated diagnostic rather than " *
                "the default decomposition for later milestones.",
            )
        end
        println(io)
        println(io, "## Identifiability and interpretation")
        println(io)
        println(
            io,
            "Reported parameter intervals are local linearized Student-t intervals derived " *
            "from the physical-parameter Jacobian. Rank, column-normalized condition, and " *
            "parameter correlation are reported separately. Narrow residual error does not " *
            "establish that a peak is a distinct chemical reaction, and highly correlated or " *
            "boundary-active parameters must not be propagated as identified components. " *
            "The derivative residuals are serially correlated, so BIC/AICc and local " *
            "intervals are conditional comparison diagnostics rather than independent-error " *
            "inference.",
        )
        println(io)
        return println(
            io,
            "M5 satisfies its synthetic recovery and visibility gates. The machine report " *
            "retains every candidate, component curve summary, bound diagnostic, uncertainty " *
            "summary, and joint-fit result for downstream review.",
        )
    end
    return path
end

toml_string(value) = "\"" * replace(String(value), "\\" => "\\\\", "\"" => "\\\"") * "\""
toml_float(value) =
    if isnan(value)
        "nan"
    elseif value == Inf
        "inf"
    elseif value == -Inf
        "-inf"
    else
        @sprintf("%.16g", value)
    end
toml_float_array(values) = "[" * join(toml_float.(values), ", ") * "]"
toml_int_array(values) = "[" * join(string.(values), ", ") * "]"
toml_bool_array(values) = "[" * join(string.(values), ", ") * "]"
toml_string_array(values) = "[" * join(toml_string.(values), ", ") * "]"

function write_machine_report(path, processed, comparisons, joint_results, config)
    experiment_by_id = Dict(experiment.source_id => experiment for experiment in processed)
    open(path, "w") do io
        println(io, "schema_version = 1")
        println(io, "generated_on = \"2026-08-17\"")
        println(io, "calibration_experiment_count = 20")
        println(io, "validation_experiment_count_used = 0")
        println(
            io,
            "selection_criterion = ",
            toml_string(config.deconvolution.selection_criterion),
        )
        println(io, "peak_counts = ", toml_int_array(config.deconvolution.peak_counts))
        println(
            io,
            "fit_conversion_range = ",
            toml_float_array(config.deconvolution.fit_conversion_range),
        )
        println(io)
        for id in sort(collect(keys(comparisons)))
            comparison = comparisons[id]
            experiment = experiment_by_id[id]
            metadata = experiment_metadata(experiment)
            println(io, "[[comparison]]")
            println(io, "experiment_id = ", toml_string(id))
            println(io, "waste_tire_dry_mass_percent = $(metadata.composition)")
            println(io, "heating_rate_kelvin_per_minute = $(metadata.rate)")
            println(
                io,
                "criterion_minimum_peak_count = $(comparison.criterion_minimum_peak_count)",
            )
            println(io, "selected_peak_count = $(comparison.selected_peak_count)")
            println(io, "status = ", toml_string(comparison.status))
            println(
                io, "criterion_values = ", toml_float_array(comparison.criterion_values)
            )
            println(
                io, "criterion_deltas = ", toml_float_array(comparison.criterion_deltas)
            )
            println(
                io,
                "structurally_eligible = ",
                toml_bool_array(comparison.structurally_eligible),
            )
            println(io, "warnings = ", toml_string_array(comparison.warnings))
            println(io)
            for result in comparison.results
                diagnostics = result.diagnostics
                println(io, "[[candidate]]")
                println(io, "experiment_id = ", toml_string(id))
                println(io, "peak_count = $(result.peak_count)")
                println(
                    io, "analysis_fingerprint = ", toml_string(result.analysis_fingerprint)
                )
                println(io, "status = ", toml_string(diagnostics.status))
                println(io, "converged = $(diagnostics.converged)")
                println(
                    io,
                    "height_kelvin_inverse = ",
                    toml_float_array(getproperty.(result.peaks, :height_K_inv)),
                )
                println(io, "skew = ", toml_float_array(getproperty.(result.peaks, :skew)))
                println(
                    io,
                    "center_kelvin = ",
                    toml_float_array(getproperty.(result.peaks, :center_K)),
                )
                println(
                    io,
                    "width_kelvin = ",
                    toml_float_array(getproperty.(result.peaks, :width_K)),
                )
                println(io, "component_area = ", toml_float_array(result.component_areas))
                println(
                    io,
                    "component_area_fraction = ",
                    toml_float_array(result.component_area_fractions),
                )
                println(
                    io,
                    "parameter_standard_error = ",
                    toml_float_array(
                        reduce(
                            vcat,
                            [
                                collect(value.standard_error) for
                                value in result.parameter_uncertainty
                            ],
                        ),
                    ),
                )
                println(
                    io,
                    "residual_sum_squares = ",
                    toml_float(diagnostics.residual_sum_squares),
                )
                println(
                    io,
                    "root_mean_square_error = ",
                    toml_float(diagnostics.root_mean_square_error),
                )
                println(io, "r_squared = ", toml_float(diagnostics.r_squared))
                println(io, "aicc = ", toml_float(diagnostics.aicc))
                println(io, "bic = ", toml_float(diagnostics.bic))
                println(io, "durbin_watson = ", toml_float(diagnostics.durbin_watson))
                println(
                    io,
                    "relative_area_error = ",
                    toml_float(diagnostics.relative_area_error),
                )
                println(io, "jacobian_rank = $(diagnostics.jacobian_rank)")
                println(io, "parameter_count = $(diagnostics.parameter_count)")
                println(
                    io, "jacobian_condition = ", toml_float(diagnostics.jacobian_condition)
                )
                println(
                    io,
                    "maximum_absolute_parameter_correlation = ",
                    toml_float(diagnostics.maximum_absolute_parameter_correlation),
                )
                println(
                    io,
                    "boundary_parameters = ",
                    toml_string_array(diagnostics.boundary_parameters),
                )
                println(io, "warnings = ", toml_string_array(diagnostics.warnings))
                println(io)
            end
        end
        for composition in (0, 25, 50, 75, 100)
            result = joint_results[composition]
            diagnostics = result.diagnostics
            println(io, "[[joint_result]]")
            println(io, "waste_tire_dry_mass_percent = $composition")
            println(io, "peak_count = $(result.peak_count)")
            println(io, "analysis_fingerprint = ", toml_string(result.analysis_fingerprint))
            println(io, "experiment_ids = ", toml_string_array(result.experiment_ids))
            println(io, "shared_skew = ", toml_float_array(result.shared_skews))
            println(io, "status = ", toml_string(diagnostics.status))
            println(io, "converged = $(diagnostics.converged)")
            println(
                io, "normalized_objective = ", toml_float(diagnostics.normalized_objective)
            )
            println(
                io,
                "independent_normalized_objective = ",
                toml_float(diagnostics.independent_normalized_objective),
            )
            println(
                io,
                "relative_objective_increase = ",
                toml_float(diagnostics.relative_objective_increase),
            )
            println(io, "warnings = ", toml_string_array(diagnostics.warnings))
            println(io)
        end
    end
    return path
end

function plot_representative(path, comparison)
    result = candidate_result(comparison, comparison.selected_peak_count)
    colors = Makie.wong_colors()
    figure = Figure(; size=(1200, 850))
    axis = Axis(
        figure[1, 1];
        title="Representative M5 decomposition — 50% waste tire, 10 K/min",
        ylabel="dα/dT (K⁻¹)",
    )
    lines!(
        axis,
        result.temperature_K .- 273.15,
        result.observed_rate_K_inv;
        color=:black,
        linewidth=1.5,
        label="Observed",
    )
    lines!(
        axis,
        result.temperature_K .- 273.15,
        result.fitted_rate_K_inv;
        color=colors[1],
        linewidth=2.5,
        label="Selected fit",
    )
    for (index, component) in enumerate(result.component_rate_K_inv)
        lines!(
            axis,
            result.temperature_K .- 273.15,
            component;
            color=colors[index + 1],
            linewidth=2,
            label="Ordered peak $index",
        )
    end
    axislegend(axis; position=:rt, framevisible=false)
    residual_axis = Axis(
        figure[2, 1]; xlabel="Temperature (°C)", ylabel="Residual (K⁻¹)", height=220
    )
    hlines!(residual_axis, [0.0]; color=:gray, linestyle=:dash)
    lines!(
        residual_axis,
        result.temperature_K .- 273.15,
        result.residual_rate_K_inv;
        color=colors[1],
    )
    linkxaxes!(axis, residual_axis)
    save(path, figure)
    return path
end

function plot_peak_count_selection(path, processed, comparisons)
    rates = [5, 10, 15, 20]
    compositions = [0, 25, 50, 75, 100]
    selected = fill(NaN, length(compositions), length(rates))
    raw = fill(NaN, size(selected))
    for experiment in processed
        metadata = experiment_metadata(experiment)
        row = findfirst(==(metadata.composition), compositions)
        column = findfirst(==(metadata.rate), rates)
        comparison = comparisons[experiment.source_id]
        selected[row, column] = comparison.selected_peak_count
        raw[row, column] = comparison.criterion_minimum_peak_count
    end
    figure = Figure(; size=(950, 650))
    axis = Axis(
        figure[1, 1];
        title="M5 peak-count selection (label shows raw BIC → structural selection)",
        xlabel="Heating rate (K/min)",
        ylabel="Waste-tire dry-mass fraction (%)",
        xticks=(eachindex(rates), string.(rates)),
        yticks=(eachindex(compositions), string.(compositions)),
    )
    heatmap!(axis, transpose(selected); colormap=:viridis, colorrange=(2, 4))
    for row in eachindex(compositions), column in eachindex(rates)
        text!(
            axis,
            column,
            row;
            text="$(round(Int, raw[row, column])) → $(round(Int, selected[row, column]))",
            align=(:center, :center),
            color=:white,
            fontsize=18,
        )
    end
    Colorbar(
        figure[1, 2];
        limits=(2, 4),
        colormap=:viridis,
        label="Selected peak count",
        ticks=2:4,
    )
    save(path, figure)
    return path
end

function main()
    config = load_config(joinpath(PROJECT_ROOT, "config", "analysis_defaults.toml"))
    catalog = load_dataset_catalog(joinpath(PROJECT_ROOT, "config", "datasets.toml"))
    raw = load_experiments(catalog; roles=[:calibration])
    processed = preprocess.(raw, Ref(config))
    comparisons = run_independent_audit(processed, config)
    joint_results = run_joint_audit(processed, comparisons, config)

    mkpath(dirname(DEFAULT_REPORT))
    mkpath(dirname(DEFAULT_MACHINE_REPORT))
    mkpath(DEFAULT_FIGURE_DIRECTORY)
    write_markdown(DEFAULT_REPORT, processed, comparisons, joint_results, config)
    write_machine_report(
        DEFAULT_MACHINE_REPORT, processed, comparisons, joint_results, config
    )
    representative = comparisons["dynamic_wt050_rate10"]
    plot_representative(
        joinpath(DEFAULT_FIGURE_DIRECTORY, "representative_deconvolution.svg"),
        representative,
    )
    plot_peak_count_selection(
        joinpath(DEFAULT_FIGURE_DIRECTORY, "peak_count_selection.svg"),
        processed,
        comparisons,
    )
    println("Wrote $(relpath(DEFAULT_REPORT, PROJECT_ROOT))")
    println("Wrote $(relpath(DEFAULT_MACHINE_REPORT, PROJECT_ROOT))")
    return println("Wrote $(relpath(DEFAULT_FIGURE_DIRECTORY, PROJECT_ROOT))/")
end

main()
