using CairoMakie
using IsoconversionalAnalysis
using Printf
using Statistics

const PROJECT_ROOT = normpath(joinpath(@__DIR__, ".."))
const DEFAULT_REPORT = joinpath(PROJECT_ROOT, "docs", "reaction_model_audit.md")
const DEFAULT_MACHINE_REPORT = joinpath(
    PROJECT_ROOT, "docs", "audits", "m6_reaction_model_results.toml"
)
const DEFAULT_FIGURE_DIRECTORY = joinpath(PROJECT_ROOT, "docs", "figures", "m6")

composition_percent(experiment) = round(Int, 100 * experiment.composition.waste_tire)
function heating_rate(experiment)
    return round(Int, experiment.diagnostics.measured_heating_rate_K_per_min)
end

function candidate_result(comparison::KineticModelComparison, model::Symbol)
    return only(filter(result -> result.model.name == model, comparison.results))
end

function parameter_value(result::KineticTripletResult, name::Symbol)
    index = findfirst(parameter -> parameter.name == name, result.parameters)
    return isnothing(index) ? NaN : result.parameters[index].estimate
end

function format_number(value; digits=3)
    return isfinite(value) ? @sprintf("%.*f", digits, value) : "not available"
end

function format_scientific(value)
    return isfinite(value) ? @sprintf("%.3e", value) : "not available"
end

function count_values(values)
    return join(
        ["`$value` × $(count(==(value), values))" for value in sort(unique(values))], ", "
    )
end

function run_audit()
    config = load_config(joinpath(PROJECT_ROOT, "config", "analysis_defaults.toml"))
    catalog = load_dataset_catalog(joinpath(PROJECT_ROOT, "config", "datasets.toml"))
    raw = load_experiments(catalog; roles=[:calibration])
    processed = preprocess.(raw, Ref(config))
    groups = Dict(
        composition => sort(
            filter(experiment -> composition_percent(experiment) == composition, processed);
            by=experiment -> experiment.source_id,
        ) for composition in (0, 25, 50, 75, 100)
    )
    comparisons = Dict(
        composition => compare_reaction_models(group, config) for
        (composition, group) in groups
    )
    reference_energies = Dict{Int,Float64}()
    for (composition, group) in groups
        starink = analyze(:starink, group, config)
        reference_energies[composition] = median(
            Float64.(collect(skipmissing(starink.activation_energy_kJ_per_mol)))
        )
    end
    compensation = Dict{String,CompensationResult}()
    for experiment in processed
        composition = composition_percent(experiment)
        compensation[experiment.source_id] = analyze_compensation(
            experiment, reference_energies[composition], config
        )
    end
    return config, processed, groups, comparisons, reference_energies, compensation
end

function write_markdown(
    path, config, processed, comparisons, reference_energies, compensation
)
    selected_models = [comparison.selected_model for comparison in values(comparisons)]
    predictive_count = count(values(comparisons)) do comparison
        selected = candidate_result(comparison, comparison.selected_model)
        return selected.diagnostics.cross_validation_log_rate_rmse <=
               config.reaction_models.maximum_cross_validation_log_rmse
    end
    extrapolated_compensation_count = count(values(compensation)) do result
        return any(
            warning -> occursin("outside the fitted compensation range", warning),
            result.warnings,
        )
    end
    open(path, "w") do io
        println(io, "# M6 kinetic-triplet and reaction-model audit")
        println(io)
        println(io, "Generated by `scripts/audit_reaction_models.jl` on 2026-08-17.")
        println(io)
        println(io, "## Scope and frozen contract")
        println(io)
        println(
            io,
            "The audit fits one overall-conversion kinetic triplet jointly to the four " *
            "dynamic heating programs for each dry-mass composition. It uses `dalpha/dt` " *
            "between exact first-upward conversion crossings from " *
            "$(config.reaction_models.fit_conversion_range[1]) to " *
            "$(config.reaction_models.fit_conversion_range[2]). The 15 ramp-and-hold " *
            "programs remain held out for M7, and no M5 peak is assigned a common reaction " *
            "identity.",
        )
        println(io)
        println(
            io,
            "Every regression contains one `ln(A / min^-1)` intercept and one activation " *
            "energy in kJ/mol. Fixed models add no fitted shape coefficient; truncated and " *
            "generalized Sestak-Berggren candidates add `(m,n)` and `(m,n,p)`. Each run " *
            "contributes at most $(config.reaction_models.maximum_points_per_experiment) " *
            "deterministic points, and nonpositive rates are counted and excluded because " *
            "their logarithm is undefined.",
        )
        println(io)
        println(
            io,
            "Synthetic gates require exact `(E, ln A, m, n)` recovery within `1e-5`, " *
            "correct noisy-model selection, finite covariance propagation, visible invalid " *
            "rates, and permutation-invariant results. Real-data predictive adequacy requires " *
            "leave-one-heating-rate-out log-rate RMSE no greater than " *
            "$(config.reaction_models.maximum_cross_validation_log_rmse).",
        )
        println(io)
        println(io, "## Multi-rate model comparison")
        println(io)
        println(io, "Final selected models: $(count_values(selected_models)).")
        println(io)
        println(
            io,
            "| Waste-tire dry-mass fraction | Raw $(uppercase(string(config.reaction_models.selection_criterion))) minimum | Selected | Status | E (kJ/mol) | ln(A/min⁻¹) | m | n | p | Fit log-RMSE | Held-out log-RMSE | Rate NRMSE | Max abs. correlation | Median DW |",
        )
        println(io, "|---:|---|---|---|---:|---:|---:|---:|---:|---:|---:|---:|---:|---:|")
        for composition in (0, 25, 50, 75, 100)
            comparison = comparisons[composition]
            selected = candidate_result(comparison, comparison.selected_model)
            diagnostics = selected.diagnostics
            println(
                io,
                "| $composition% | `$(comparison.criterion_minimum_model)` | `$(comparison.selected_model)` | `$(comparison.status)` | $(format_number(parameter_value(selected, :activation_energy_kJ_per_mol); digits=2)) | $(format_number(parameter_value(selected, :log_preexponential_per_min); digits=3)) | $(format_number(parameter_value(selected, :m); digits=3)) | $(format_number(parameter_value(selected, :n); digits=3)) | $(format_number(parameter_value(selected, :p); digits=3)) | $(format_number(diagnostics.log_rate_rmse; digits=3)) | $(format_number(diagnostics.cross_validation_log_rate_rmse; digits=3)) | $(format_number(diagnostics.cross_validation_relative_rate_rmse; digits=3)) | $(format_number(diagnostics.maximum_absolute_parameter_correlation; digits=4)) | $(format_number(diagnostics.median_durbin_watson; digits=3)) |",
            )
        end
        println(io)
        println(
            io, "![Representative kinetic fit](figures/m6/representative_kinetic_fit.svg)"
        )
        println(io)
        println(io, "![Reaction-model comparison](figures/m6/model_selection.svg)")
        println(io)
        if predictive_count == length(comparisons)
            println(
                io,
                "Every selected single-triplet model passes the held-out-rate gate. These " *
                "models may proceed to integrated M7 validation without refitting.",
            )
        elseif predictive_count == 0
            println(
                io,
                "All five selected single-triplet models fail the held-out-rate gate. " *
                "M6 therefore rejects a constant kinetic triplet as the default predictive " *
                "description for these data. M7 must retain these fits only as descriptive " *
                "baselines and evaluate the conversion-dependent isoconversional description.",
            )
        else
            println(
                io,
                "At least one selected single-triplet model fails the held-out-rate gate. " *
                "M6 therefore treats the selected equations as descriptive baselines, not " *
                "validated predictive mechanisms. M7 must compare them with the existing " *
                "conversion-dependent isoconversional description.",
            )
        end
        println(io)
        println(io, "## Compensation-effect diagnostic")
        println(io)
        println(
            io,
            "The legacy invariant-parameter idea is evaluated on every single heating-rate " *
            "run using the fixed registry models. The independent reference energy is the " *
            "median Starink value for the composition. These estimates are not substituted " *
            "for the directly fitted multi-rate pre-exponential factor.",
        )
        println(io)
        println(
            io,
            "The reference energy lies outside the single-rate compensation-model energy " *
            "span in $extrapolated_compensation_count of $(length(compensation)) runs. " *
            "Those values are extrapolations with wide conditional intervals, not accepted " *
            "kinetic constants.",
        )
        println(io)
        println(
            io,
            "| Experiment | Waste-tire dry-mass fraction | Rate (K/min) | Reference E (kJ/mol) | Compensation R² | Estimated ln(A/min⁻¹) | Estimated A (min⁻¹) | 95% A interval (min⁻¹) |",
        )
        println(io, "|---|---:|---:|---:|---:|---:|---:|---:|")
        for experiment in sort(processed; by=value -> value.source_id)
            composition = composition_percent(experiment)
            result = compensation[experiment.source_id]
            println(
                io,
                "| `$(experiment.source_id)` | $composition% | $(heating_rate(experiment)) | $(format_number(reference_energies[composition]; digits=2)) | $(format_number(result.regression.r_squared; digits=4)) | $(format_number(result.estimated_log_preexponential_per_min; digits=3)) | $(format_scientific(result.estimated_preexponential_per_min)) | $(format_scientific(result.confidence_lower_preexponential_per_min))–$(format_scientific(result.confidence_upper_preexponential_per_min)) |",
            )
        end
        println(io)
        println(io, "![Compensation diagnostic](figures/m6/compensation_diagnostic.svg)")
        println(io)
        println(io, "## Interpretation")
        println(io)
        println(
            io,
            "Parameter intervals are local Student-t intervals from the log-linear design. " *
            "They are conditional on the model and treat densely sampled, serially correlated " *
            "derivative points as independent. Rank, normalized condition, parameter " *
            "correlation, Durbin-Watson, information criteria, and heating-rate-level " *
            "cross-validation are therefore retained separately.",
        )
        println(io)
        return println(
            io,
            "A fitted reaction-function label is an empirical equation, not a demonstrated " *
            "solid-state mechanism. The machine report retains all 95 candidates, every " *
            "held-out-rate result, and all compensation pairs.",
        )
    end
    return path
end

toml_string(value) = "\"" * replace(String(value), "\\" => "\\\\", "\"" => "\\\"") * "\""
toml_float(value) =
    if isnan(value)
        "nan"
    elseif value == Inf
        "inf"
    elseif value == -Inf
        "-inf"
    else
        @sprintf("%.16g", value)
    end
toml_float_array(values) = "[" * join(toml_float.(values), ", ") * "]"
toml_string_array(values) = "[" * join(toml_string.(values), ", ") * "]"
toml_bool_array(values) = "[" * join(string.(values), ", ") * "]"

function write_machine_report(
    path, config, processed, comparisons, reference_energies, compensation
)
    experiment_by_id = Dict(experiment.source_id => experiment for experiment in processed)
    open(path, "w") do io
        println(io, "schema_version = 1")
        println(io, "generated_on = \"2026-08-17\"")
        println(io, "calibration_experiment_count = 20")
        println(io, "validation_experiment_count_used = 0")
        println(io, "candidate_model_count = ", length(config.reaction_models.models))
        println(
            io,
            "fit_conversion_range = ",
            toml_float_array(config.reaction_models.fit_conversion_range),
        )
        println(
            io,
            "selection_criterion = ",
            toml_string(config.reaction_models.selection_criterion),
        )
        println(
            io,
            "maximum_cross_validation_log_rmse = ",
            toml_float(config.reaction_models.maximum_cross_validation_log_rmse),
        )
        for composition in (0, 25, 50, 75, 100)
            comparison = comparisons[composition]
            println(io)
            println(io, "[[comparison]]")
            println(io, "waste_tire_dry_mass_percent = $composition")
            println(io, "experiment_ids = ", toml_string_array(comparison.experiment_ids))
            println(
                io,
                "criterion_minimum_model = ",
                toml_string(comparison.criterion_minimum_model),
            )
            println(io, "selected_model = ", toml_string(comparison.selected_model))
            println(io, "status = ", toml_string(comparison.status))
            println(
                io, "criterion_values = ", toml_float_array(comparison.criterion_values)
            )
            println(
                io, "criterion_deltas = ", toml_float_array(comparison.criterion_deltas)
            )
            println(
                io,
                "structurally_eligible = ",
                toml_bool_array(comparison.structurally_eligible),
            )
            println(io, "warnings = ", toml_string_array(comparison.warnings))
            println(
                io, "analysis_fingerprint = ", toml_string(comparison.analysis_fingerprint)
            )
            for (result, eligible) in
                zip(comparison.results, comparison.structurally_eligible)
                diagnostics = result.diagnostics
                println(io)
                println(io, "[[candidate]]")
                println(io, "waste_tire_dry_mass_percent = $composition")
                println(io, "model = ", toml_string(result.model.name))
                println(io, "family = ", toml_string(result.model.family))
                println(io, "structurally_eligible = $eligible")
                println(io, "status = ", toml_string(diagnostics.status))
                println(
                    io,
                    "parameter_names = ",
                    toml_string_array(getproperty.(result.parameters, :name)),
                )
                println(
                    io,
                    "parameter_estimates = ",
                    toml_float_array(getproperty.(result.parameters, :estimate)),
                )
                println(
                    io,
                    "parameter_standard_errors = ",
                    toml_float_array(getproperty.(result.parameters, :standard_error)),
                )
                println(
                    io,
                    "confidence_lower = ",
                    toml_float_array(getproperty.(result.parameters, :confidence_lower)),
                )
                println(
                    io,
                    "confidence_upper = ",
                    toml_float_array(getproperty.(result.parameters, :confidence_upper)),
                )
                println(io, "point_count = ", diagnostics.point_count)
                println(
                    io,
                    "excluded_nonpositive_rate_count = ",
                    diagnostics.excluded_nonpositive_rate_count,
                )
                println(io, "design_rank = ", diagnostics.design_rank)
                println(io, "parameter_count = ", diagnostics.parameter_count)
                println(
                    io,
                    "normalized_design_condition = ",
                    toml_float(diagnostics.normalized_design_condition),
                )
                println(
                    io,
                    "maximum_absolute_parameter_correlation = ",
                    toml_float(diagnostics.maximum_absolute_parameter_correlation),
                )
                println(io, "log_rate_rmse = ", toml_float(diagnostics.log_rate_rmse))
                println(
                    io, "log_rate_r_squared = ", toml_float(diagnostics.log_rate_r_squared)
                )
                println(
                    io, "relative_rate_rmse = ", toml_float(diagnostics.relative_rate_rmse)
                )
                println(
                    io,
                    "median_durbin_watson = ",
                    toml_float(diagnostics.median_durbin_watson),
                )
                println(io, "aicc = ", toml_float(diagnostics.aicc))
                println(io, "bic = ", toml_float(diagnostics.bic))
                println(
                    io,
                    "cross_validation_log_rate_rmse = ",
                    toml_float(diagnostics.cross_validation_log_rate_rmse),
                )
                println(
                    io,
                    "cross_validation_relative_rate_rmse = ",
                    toml_float(diagnostics.cross_validation_relative_rate_rmse),
                )
                println(io, "warnings = ", toml_string_array(diagnostics.warnings))
                println(
                    io, "analysis_fingerprint = ", toml_string(result.analysis_fingerprint)
                )
                for validation in result.validations
                    println(io)
                    println(io, "[[validation]]")
                    println(io, "waste_tire_dry_mass_percent = $composition")
                    println(io, "model = ", toml_string(result.model.name))
                    println(io, "experiment_id = ", toml_string(validation.experiment_id))
                    println(io, "point_count = ", validation.point_count)
                    println(io, "log_rate_rmse = ", toml_float(validation.log_rate_rmse))
                    println(
                        io,
                        "relative_rate_rmse = ",
                        toml_float(validation.relative_rate_rmse),
                    )
                    println(
                        io,
                        "mean_log_rate_bias = ",
                        toml_float(validation.mean_log_rate_bias),
                    )
                end
            end
        end
        for experiment_id in sort(collect(keys(compensation)))
            result = compensation[experiment_id]
            experiment = experiment_by_id[experiment_id]
            println(io)
            println(io, "[[compensation]]")
            println(io, "experiment_id = ", toml_string(experiment_id))
            println(io, "waste_tire_dry_mass_percent = ", composition_percent(experiment))
            println(io, "heating_rate_kelvin_per_minute = ", heating_rate(experiment))
            println(io, "model_names = ", toml_string_array(result.model_names))
            println(
                io,
                "model_activation_energies_kilojoule_per_mole = ",
                toml_float_array(result.model_activation_energies_kJ_per_mol),
            )
            println(
                io,
                "model_log_preexponentials_per_minute = ",
                toml_float_array(result.model_log_preexponentials_per_min),
            )
            println(
                io,
                "reference_activation_energy_kilojoule_per_mole = ",
                toml_float(result.reference_activation_energy_kJ_per_mol),
            )
            println(
                io,
                "estimated_log_preexponential_per_minute = ",
                toml_float(result.estimated_log_preexponential_per_min),
            )
            println(
                io,
                "estimated_preexponential_per_minute = ",
                toml_float(result.estimated_preexponential_per_min),
            )
            println(
                io,
                "confidence_lower_preexponential_per_minute = ",
                toml_float(result.confidence_lower_preexponential_per_min),
            )
            println(
                io,
                "confidence_upper_preexponential_per_minute = ",
                toml_float(result.confidence_upper_preexponential_per_min),
            )
            println(
                io,
                "regression_slope_mole_per_kilojoule = ",
                toml_float(result.regression.slope),
            )
            println(io, "regression_intercept = ", toml_float(result.regression.intercept))
            println(io, "regression_r_squared = ", toml_float(result.regression.r_squared))
            println(io, "warnings = ", toml_string_array(result.warnings))
            println(io, "analysis_fingerprint = ", toml_string(result.analysis_fingerprint))
        end
    end
    return path
end

function selected_colors()
    return Makie.wong_colors()
end

function write_representative_figure(path, processed, comparison)
    result = candidate_result(comparison, comparison.selected_model)
    experiment_by_id = Dict(experiment.source_id => experiment for experiment in processed)
    figure = Figure(; size=(1000, 760))
    axis_rate = Axis(
        figure[1, 1];
        xlabel="Conversion, alpha",
        ylabel="dalpha/dt (min⁻¹)",
        title="Representative M6 fit — 50% waste tire",
        yscale=log10,
    )
    axis_residual = Axis(
        figure[2, 1]; xlabel="Conversion, alpha", ylabel="Log-rate residual"
    )
    colors = selected_colors()
    for (color_index, experiment_id) in enumerate(result.experiment_ids)
        indices = findall(==(experiment_id), result.point_experiment_ids)
        rate = heating_rate(experiment_by_id[experiment_id])
        scatter!(
            axis_rate,
            result.alpha[indices],
            result.observed_rate_per_min[indices];
            color=(colors[color_index], 0.45),
            markersize=4,
            label="$rate K/min observed",
        )
        lines!(
            axis_rate,
            result.alpha[indices],
            result.fitted_rate_per_min[indices];
            color=colors[color_index],
            linewidth=2,
            label="$rate K/min fitted",
        )
        lines!(
            axis_residual,
            result.alpha[indices],
            result.log_rate_residual[indices];
            color=colors[color_index],
            linewidth=1.5,
        )
    end
    hlines!(axis_residual, [0.0]; color=:gray45, linestyle=:dash)
    axislegend(axis_rate; position=:rb, nbanks=2)
    save(path, figure)
    return path
end

function write_model_selection_figure(path, comparisons, config)
    compositions = [0, 25, 50, 75, 100]
    models = config.reaction_models.models
    deltas = [
        min(comparisons[composition].criterion_deltas[index], 100.0) for
        composition in compositions, index in eachindex(models)
    ]
    figure = Figure(; size=(1200, 560))
    axis = Axis(
        figure[1, 1];
        xticks=(eachindex(models), string.(models)),
        yticks=(eachindex(compositions), string.(compositions)),
        xlabel="Reaction-model candidate",
        ylabel="Waste-tire dry-mass fraction (%)",
        title="M6 BIC deltas (capped at 100)",
        xticklabelrotation=pi / 3,
    )
    heatmap_plot = heatmap!(
        axis, eachindex(models), eachindex(compositions), transpose(deltas)
    )
    Colorbar(figure[1, 2], heatmap_plot; label="Delta BIC")
    save(path, figure)
    return path
end

function write_compensation_figure(path, processed, compensation)
    experiment = only(filter(value -> value.source_id == "dynamic_wt050_rate10", processed))
    result = compensation[experiment.source_id]
    minimum_energy, maximum_energy = extrema(result.model_activation_energies_kJ_per_mol)
    energy_line = collect(range(minimum_energy, maximum_energy; length=200))
    log_a_line = @. result.regression.intercept + result.regression.slope * energy_line
    figure = Figure(; size=(800, 560))
    axis = Axis(
        figure[1, 1];
        xlabel="Single-rate fitted E (kJ/mol)",
        ylabel="Single-rate fitted ln(A/min⁻¹)",
        title="Compensation diagnostic — 50% waste tire, 10 K/min",
    )
    scatter!(
        axis,
        result.model_activation_energies_kJ_per_mol,
        result.model_log_preexponentials_per_min;
        color=:black,
        markersize=9,
        label="Fixed-model pairs",
    )
    lines!(axis, energy_line, log_a_line; color=:steelblue, linewidth=2, label="OLS line")
    scatter!(
        axis,
        [result.reference_activation_energy_kJ_per_mol],
        [result.estimated_log_preexponential_per_min];
        color=:orangered,
        marker=:star5,
        markersize=18,
        label="Starink-reference evaluation",
    )
    axislegend(axis; position=:rb)
    save(path, figure)
    return path
end

function main()
    config, processed, _, comparisons, reference_energies, compensation = run_audit()
    mkpath(dirname(DEFAULT_REPORT))
    mkpath(dirname(DEFAULT_MACHINE_REPORT))
    mkpath(DEFAULT_FIGURE_DIRECTORY)
    write_markdown(
        DEFAULT_REPORT, config, processed, comparisons, reference_energies, compensation
    )
    write_machine_report(
        DEFAULT_MACHINE_REPORT,
        config,
        processed,
        comparisons,
        reference_energies,
        compensation,
    )
    write_representative_figure(
        joinpath(DEFAULT_FIGURE_DIRECTORY, "representative_kinetic_fit.svg"),
        processed,
        comparisons[50],
    )
    write_model_selection_figure(
        joinpath(DEFAULT_FIGURE_DIRECTORY, "model_selection.svg"), comparisons, config
    )
    write_compensation_figure(
        joinpath(DEFAULT_FIGURE_DIRECTORY, "compensation_diagnostic.svg"),
        processed,
        compensation,
    )
    println("Wrote docs/reaction_model_audit.md")
    println("Wrote docs/audits/m6_reaction_model_results.toml")
    return println("Wrote docs/figures/m6/")
end

main()
